# The config recipe.
# https://rasa.com/docs/rasa/model-configuration/
recipe: default.v1

# The assistant project unique identifier
# This default value must be replaced with a unique assistant name within your deployment
assistant_id: 20240207-172458-violent-appreciation

# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: en


pipeline:
  - name: WhitespaceTokenizer  # Splits sentences into tokens (words)
  - name: RegexFeaturizer  # Uses regular expressions to help the model recognize specific patterns
  - name: LexicalSyntacticFeaturizer  # Adds features based on part of speech tags, which can help understand the structure of smack talk
  - name: CountVectorsFeaturizer  # Creates bag-of-words feature representations
  - name: CountVectorsFeaturizer
    analyzer: char_wb
    min_ngram: 1
    max_ngram: 4  # Helps in understanding affixes and morphemes, useful for capturing slang or abbreviations common in smack talk
  - name: LanguageModelFeaturizer
    model_name: "bert"
    model_weights: "bert-base-uncased"  # Leverages pre-trained BERT embeddings to grasp the context better
  - name: DIETClassifier
    epochs: 200
    constrain_similarities: True  # The main model for intent classification and entity extraction
  - name: EntitySynonymMapper  # Maps different phrases meaning the same thing to the same entity value
  - name: ResponseSelector
    epochs: 200  # Used for retrieving responses from a predefined list of utterances


# # No configuration for the NLU pipeline was provided. The following default pipeline was used to train your model.
# # If you'd like to customize it, uncomment and adjust the pipeline.
# # See https://rasa.com/docs/rasa/tuning-your-model for more information.
#   - name: WhitespaceTokenizer
#   - name: RegexFeaturizer
#   - name: LexicalSyntacticFeaturizer
#   - name: CountVectorsFeaturizer
#   - name: CountVectorsFeaturizer
#     analyzer: char_wb
#     min_ngram: 1
#     max_ngram: 4
#   - name: DIETClassifier
#     epochs: 100
#     constrain_similarities: true
#   - name: EntitySynonymMapper
#   - name: ResponseSelector
#     epochs: 100
#     constrain_similarities: true
#   - name: FallbackClassifier
#     threshold: 0.3
#     ambiguity_threshold: 0.1

# Configuration for Rasa Core.
# https://rasa.com/docs/rasa/core/policies/

policies:
  - name: MemoizationPolicy
    max_history: 5  # Remembers and utilizes specific sequences of dialogue
  - name: TEDPolicy
    max_history: 5
    epochs: 100
    constrain_similarities: true  # Predicts the next action based on the dialogue context using a transformer model
  - name: RulePolicy
    # Enables following specific conversation rules for predictable interactions


# # No configuration for policies was provided. The following default policies were used to train your model.
# # If you'd like to customize them, uncomment and adjust the policies.
# # See https://rasa.com/docs/rasa/policies for more information.
#   - name: MemoizationPolicy
#   - name: RulePolicy
#   - name: UnexpecTEDIntentPolicy
#     max_history: 5
#     epochs: 100
#   - name: TEDPolicy
#     max_history: 5
#     epochs: 100
#     constrain_similarities: true
